### ISSUE TITLE
Credit Class Gift Voucher does not subtract total

### ISSUE THREAD

**Issue by newburns** [newburns/osCommerce-234-bootstrap-wADDONS#14]
Credit Class Gift Voucher add-on does not subtract amount from the Total.
Also, the Bootstrap CSS does not fit properly on the payments page. Needs UI rework

**Comment by tmccaff** [comment]
Ok so I am guess Gift Vouchers not working? I tested it and it's not subtracting it. I will try and look at that as well tonight.

**Comment by newburns** [comment]
I think you solved this one?
@tmccaff

**Comment by tmccaff** [comment]
I have tested coupon function not the gift vouchers as of yet

**Comment by tmccaff** [comment]
Works, fixed

**Comment by tmccaff** [comment]
It substracts the total. However, I see the problem when you view the order on your account. Is that where you mean?

**Comment by newburns** [comment]
Yes

**Comment by tmccaff** [comment]
ok it's still a issue. I will look into it. I have a idea for coupon and I am working on it. However, I like at least the function working before making it look pretty lol

**Comment by tmccaff** [comment]
It also does the same thing at checkout confirmation. I am guessing it has to be in order_total.php or the ot_gv module itself.

**Comment by tmccaff** [comment]
Fixed. Will commit soon
