### ISSUE TITLE
sorting doesn't work

### ISSUE THREAD

**Issue by cbruyndoncx** [newburns/osCommerce-234-bootstrap-wADDONS#43]
installed 
looking at dvd movies / action which has several items
top right sort pull down isn't functioning (latest firefox)
also the default list or grid view is not highlighted

**Comment by newburns** [comment]
Try to remove the code changes for ../index.php at line 184 ~199. There was new code to change the default sorting option. The bug may have been introduced there.
Report back.

**Comment by cbruyndoncx** [comment]
I went to find some of burts templates and see there that the sort dropdown works fine;
in my install, no javascript is firing on the sort button perhaps some script is missing, or the page doesn't validate without any boxes being active ?
