### ISSUE TITLE
CCGV addon Paypal needs to be worked

### ISSUE THREAD

**Issue by tmccaff** [newburns/osCommerce-234-bootstrap-wADDONS#51]
Paypal needs to be altered for CCGV addon

**Comment by newburns** [comment]
Working on it. Trying to merge the gburton Master first. New email template
system bypasses the mail manager add-on

**Comment by tmccaff** [comment]
I have done it; need to test it though

**Comment by tmccaff** [comment]
I don't know if the code is messed up in one of the pages or it's paypal itself. It is weird that it doesn't unregister the coupon and store doest redeem coupon through paypal. I am guessing it has to be something I am missing in paypal itself. When you have time take a look at the code I applied to paypal standard. Thanks

**Comment by tmccaff** [comment]
Paypal is not removing coupon upon checkout. Basically the coupon is still in cart even if you dont enter it. I am not sure if I have paypal code wrong or something is wrong with the code itself. I am going to try discount coupon mod instead to see what happens.

**Comment by tmccaff** [comment]
It works and tested
