### ISSUE TITLE
Latest commit has many errors

### ISSUE THREAD

**Issue by newburns** [newburns/osCommerce-234-bootstrap-wADDONS#62]
We need to address "reverting" the latest commit.
There are several files with Git "Conflict" comments.
"<<<<<<< HEAD"
There also seems to be a bad rebase somewhere in your master. As the latest commit adds the same changes from this repo.

**Comment by tmccaff** [comment]
I know fixing as we speak.

**Comment by newburns** [comment]
Will we be better to revert this commit, rebase your master, and complete a new PR?
I'm not really proficient in github, but I do know that you do not want any conflicts in the HEAD.

**Comment by tmccaff** [comment]
ok reverted did that work?

**Comment by newburns** [comment]
Yep.
Looks like I have one as well.
I may try to revert to before the latest update to gBurton.
Then you can add your final commit, and I will add the final gBurton commit. Looking to see how to do that without adding to the commit count

**Comment by newburns** [comment]
Looks like what I need to do is a Git reset to before https://github.com/newburns/osCommerce-234-bootstrap-wADDONS/commit/ceb3662d1e104f7ebf900b7af8e10ceaf235c471

**Comment by tmccaff** [comment]
I think I know what I did to make that happen. I pulled a request from yours before I commted mine which caused a conflict. isnt it like git rebase -i

**Comment by newburns** [comment]
Not sure how to fully use rebase.
But, let me know if you are "against or for" me running:
git reset --hard 1c5a00faa12a87de45ba8b77a199f6c7e6932d22

**Comment by tmccaff** [comment]
you want me to run this on my end?

**Comment by newburns** [comment]
nope.
I'm going to run on the master.
It will reset the history back and remove changes made today.
1. Then I will update to latest gBurton
2. You can rebase and pull the changes
3. We can merge back to this master

**Comment by tmccaff** [comment]
ok

**Comment by newburns** [comment]
No, that's a bad idea.
We should just fix it from where it is now.

**Comment by tmccaff** [comment]
k is it the last commit on my end or?

**Comment by newburns** [comment]
We are good, go ahead and push your changes once you've tested it.
Also, are you sure teh filename removal is working?

**Comment by tmccaff** [comment]
K. Yes filename removal is working.

**Comment by tmccaff** [comment]
However, I am not going to commit that change as of yet. I am going to check CCGV more to make sure it's working in both vouchers and coupons as it should.
