### ISSUE TITLE
Fatal error: Call to a member function count_contents() on a non-object in bm_shopping_cart.php

### ISSUE THREAD

**Issue by tmccaff** [newburns/osCommerce-234-bootstrap-wADDONS#68]
this is what the line is:

if ($cart->count_contents() > 0) {

This is what happens when you install the shopping cart box.

**Comment by tmccaff** [comment]
I know what is wrong with it. However, isn't it supposed to show Order, subtotal than discount?

I am not sure what this is supposed to look like. However, I am going to possibly modify this module.

**Comment by newburns** [comment]
I think it should be order, discount, subtotal, then total.
You cannot discount after tax. Tax is applied to subtotal

**Comment by tmccaff** [comment]
something is wrong with shopping cart box. I figured out that error as you commented out global $cart which it needs. However, it isn't showing discount, total, etc. Or is it supposed to? I am talking about bm_shopping cart box

**Comment by tmccaff** [comment]
fixed
