### ISSUE TITLE
Vouchers are not being qued

### ISSUE THREAD

**Issue by tmccaff** [newburns/osCommerce-234-bootstrap-wADDONS#77]
It looks like the whole voucher system isn't working properly.

**Comment by newburns** [comment]
Check the git history for ot_gv PHP. I may have disabled it when o couldn't
get it to work.
Also check order_total.php

**Comment by tmccaff** [comment]
Ok test this on your end. Go to order total modules in store. Gift voucher sort order change to 3. See if it works. Thanks

**Comment by tmccaff** [comment]
Fixed. Will commit soon
